/**
 * End-to-end local test script.
 * Uses SP1_PROVER=mock proof + a MockSP1Verifier to test the full
 * PassportVerifier contract flow on a local Hardhat network.
 *
 * Run with:
 *   npx hardhat run scripts/test-local.js --network localhost
 * (after starting: npx hardhat node)
 */
const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
    const [deployer] = await hre.ethers.getSigners();
    console.log("Deployer / Signer:", deployer.address);

    // 1. Load the mock proof generated by SP1_PROVER=mock
    const proofPath = path.join(__dirname, "../proofs/passport_proof_evm.json");
    if (!fs.existsSync(proofPath)) {
        console.error("Proof file not found:", proofPath);
        process.exit(1);
    }
    const proofData = JSON.parse(fs.readFileSync(proofPath, "utf8"));
    const proof = "0x" + proofData.proof.replace(/^0x/, "");
    const publicValues = "0x" + proofData.publicValues.replace(/^0x/, "");
    const vkey = proofData.vkey;
    console.log("\nLoaded proof:");
    console.log("  VKey:", vkey);
    console.log("  Public values length:", (publicValues.length - 2) / 2, "bytes");
    console.log("  Proof length:", (proof.length - 2) / 2, "bytes (mock = 0 expected)");

    // Decode public values to show what the proof claims
    // publicValues is ABI-encoded with a 32-byte offset prefix (0x20).
    // The contract handles this by slicing off the prefix inside verifyPassport.
    // For JS decoding, we skip the first 32 bytes (64 hex chars after "0x").
    const ABI = hre.ethers.AbiCoder.defaultAbiCoder();
    // publicValues may or may not have "0x" prefix
    const pubHex = proofData.publicValues.startsWith("0x")
        ? proofData.publicValues.slice(2)
        : proofData.publicValues;
    // Check if first 32 bytes == 0x20 (offset prefix added by SP1) and skip it
    const firstWord = BigInt("0x" + pubHex.slice(0, 64));
    const decodeHex = "0x" + (firstWord === 32n ? pubHex.slice(64) : pubHex);
    const decoded = ABI.decode(
        ["bool", "bool", "bytes32", "address", "uint256", "string", "uint256"],
        decodeHex
    );
    console.log("\nProof claims:");
    console.log("  isOverMinAge     :", decoded[0]);
    console.log("  isNationalityMatch:", decoded[1]);
    console.log("  identityCommitment:", decoded[2]);
    console.log("  walletAddress    :", decoded[3]);
    console.log("  minAge           :", decoded[4].toString());
    console.log("  targetNationality:", decoded[5]);
    console.log("  timestamp        :", decoded[6].toString(), "→", new Date(Number(decoded[6]) * 1000).toISOString());

    // 2. Deploy MockSP1Verifier
    console.log("\nDeploying MockSP1Verifier...");
    const MockVerifier = await hre.ethers.getContractFactory("MockSP1Verifier");
    const mockVerifier = await MockVerifier.deploy();
    await mockVerifier.waitForDeployment();
    console.log("  MockSP1Verifier deployed at:", await mockVerifier.getAddress());

    // 3. Deploy PassportVerifier with mock verifier + vkey
    console.log("\nDeploying PassportVerifier...");
    const PassportVerifier = await hre.ethers.getContractFactory("PassportVerifier");
    const passportVerifier = await PassportVerifier.deploy(
        await mockVerifier.getAddress(),
        vkey
    );
    await passportVerifier.waitForDeployment();
    console.log("  PassportVerifier deployed at:", await passportVerifier.getAddress());

    // 4. The proof binds to a specific wallet address.
    //    We need to impersonate that wallet to call verifyPassport.
    const boundWallet = decoded[3]; // the walletAddress from proof
    console.log("\nImpersonating proof-bound wallet:", boundWallet);
    await hre.network.provider.request({
        method: "hardhat_impersonateAccount",
        params: [boundWallet],
    });
    // Fund it so it can pay gas
    await hre.network.provider.send("hardhat_setBalance", [
        boundWallet,
        "0x1000000000000000000", // 1 ETH
    ]);
    const boundSigner = await hre.ethers.getSigner(boundWallet);

    // 5. Call verifyPassport
    console.log("\nCalling PassportVerifier.verifyPassport()...");
    try {
        const tx = await passportVerifier.connect(boundSigner).verifyPassport(
            publicValues,
            proof
        );
        console.log("  Transaction hash:", tx.hash);
        const receipt = await tx.wait();
        console.log("  Gas used:", receipt.gasUsed.toString());

        // Check the IdentityVerified event
        const events = receipt.logs
            .map(log => {
                try { return passportVerifier.interface.parseLog(log); } catch { return null; }
            })
            .filter(Boolean);

        console.log("\nProof verified successfully!");
        for (const ev of events) {
            if (ev.name === "IdentityVerified") {
                console.log("\nIdentityVerified event:");
                console.log("  identityCommitment:", ev.args.identityCommitment);
                console.log("  wallet            :", ev.args.wallet);
                console.log("  nationality       :", ev.args.nationality || "(none - mismatch)");
                console.log("  isAdult           :", ev.args.isAdult);
            }
        }

        // Query the stored identity
        const identity = await passportVerifier.identities(decoded[2]);
        console.log("\nOn-chain identity record:");
        console.log("  isVerified           :", identity.isVerified);
        console.log("  boundWallet          :", identity.boundWallet);
        console.log("  nationality          :", identity.nationality || "(none - mismatch)");
        console.log("  isAdult              :", identity.isAdult);
        console.log("  verificationTimestamp:", new Date(Number(identity.verificationTimestamp) * 1000).toISOString());

    } catch (error) {
        console.error("\nVerification failed:", error.message);
        if (error.data) {
            try {
                const decoded = passportVerifier.interface.parseError(error.data);
                console.error("  Contract error:", decoded.name, decoded.args);
            } catch { /* ignore */ }
        }
        process.exit(1);
    }
}

main()
    .then(() => process.exit(0))
    .catch(err => { console.error(err); process.exit(1); });
